version: 2
jobs:
  build:
    working_directory: ~/station
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - checkout
      - run:
          name: "Installing Dependencies"
          command: npm install
      - run:
          name: "Running Eslint"
          command: npm run lint